<?php
$tradeProperty_config = array(3=>'科目交易',4=>'税金交易',5=>'用户交易');
$tradeType_config = array(1=>'存入',2=>'支出');
//日期
$StartDate=$_GET['StartDate']!=''?$_GET['StartDate']:date('Y-m').'-01';
$EndDate=$_GET['EndDate']!=''?$_GET['EndDate']:date('Y-m-d');
//日期格式2(带时分秒)
$StartDate2=$_GET['StartDate']!=''?$_GET['StartDate']:date('Y-m').'-01 00:00:00';
$EndDate2=$_GET['EndDate']!=''?$_GET['EndDate']:date('Y-m-d H:i:s');

$config_array = array(
	'kkyoo_kmoney'=>array(
		'kmoney_balance'=>array(
			'table_name'=>'用户余额表',
			'col'=>array('uin'=>'用户ID','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Uin','Balance_status'),
			'statistics'=>array(
				'name'=>'用户总余额',
				'data'=>array(
					array('field'=>'last_balance')
				)
			),
			'child_id'=>101
		),
		'kmoney_parent_balance'=>array(
			'table_name'=>'科目余额表',
			'col'=>array('bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Core_three'),
			'statistics'=>array(
				'name'=>'科目总余额',
				'data'=>array(
					array('field'=>'last_balance')
				)	
			),
			'child_id'=>102
		),
		'kmoney_running'=>array(
			'table_name'=>'科目流水表',
			'col'=>array('uptime'=>'时间','bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','child_name'=>'四级科目','trade_property'=>'交易属性','trade_type'=>'借贷','trade_money'=>'发生金额','parent_balance'=>'科目余额','uin'=>'用户ID','last_balance'=>'用户余额','trade_desc'=>'备注'),
			'searchField'=>array('Uin','Core_four','Trade_info','Date_range2'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'trade_money','other_where'=>'trade_type=1'),
					array('name'=>'总支出','field'=>'trade_money','other_where'=>'trade_type=2')	
				)
			),
			'child_id'=>103
		),
		'kmoney_user_detail'=>array(
			'table_name'=>'用户明细平衡表',
			'col'=>array('uin'=>'用户ID','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Uin','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>104
		),
		'kmoney_user_ledger'=>array(
			'table_name'=>'用户总账平衡表',
			'col'=>array('deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>105
		),
		'kmoney_parent_detail'=>array(
			'table_name'=>'科目明细平衡表',
			'col'=>array('bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Core_three','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>106
		),
		'kmoney_parent_ledger'=>array(
			'table_name'=>'科目总账平衡表',
			'col'=>array('deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>107
		),
		'kmoney_net_summary'=>array(
			'table_name'=>'汇总净平衡表',
			'col'=>array('deposit_money'=>'平台净存入','account_deposit'=>'账户净存入','pay_money'=>'平台净支出','account_pay'=>'账户净支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>108
		)
	),
	'kkyoo_voucher'=>array(
		'voucher_balance'=>array(
			'table_name'=>'用户余额表',
			'col'=>array('group_id'=>'站ID','uin'=>'用户ID','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Uin','Balance_status'),
			'statistics'=>array(
				'name'=>'用户总余额',
				'data'=>array(
					array('field'=>'last_balance')	
				)
			),
			'child_id'=>101
		),
		'voucher_parent_balance'=>array(
			'table_name'=>'科目余额表',
			'col'=>array('group_id'=>'站ID','bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Core_three'),
			'statistics'=>array(
				'name'=>'科目总余额',
				'data'=>array(
					array('field'=>'last_balance')
				)	
			),
			'child_id'=>102
		),
		'voucher_running'=>array(
			'table_name'=>'科目流水表',
			'col'=>array('group_id'=>'站ID','uin'=>'用户ID','uptime'=>'时间','bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','child_name'=>'四级科目','trade_property'=>'交易属性','trade_type'=>'借贷','trade_money'=>'发生金额','parent_balance'=>'科目余额','last_balance'=>'用户余额','trade_desc'=>'备注'),
			'searchField'=>array('Group_id','Uin','Core_four','Trade_info','Date_range2'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'trade_money','other_where'=>'trade_type=1'),
					array('name'=>'总支出','field'=>'trade_money','other_where'=>'trade_type=2')	
				)
			),
			'child_id'=>103
		),
		'voucher_user_detail'=>array(
			'table_name'=>'用户明细平衡表',
			'col'=>array('group_id'=>'站ID','uin'=>'用户ID','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Uin','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>104
		),
		'voucher_user_summary'=>array(
			'table_name'=>'用户汇总平衡表',
			'col'=>array('group_id'=>'站ID','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>105
		),
		'voucher_parent_detail'=>array(
			'table_name'=>'科目明细平衡表',
			'col'=>array('group_id'=>'站ID','bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Core_three','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>107
		),
		'voucher_parent_ledger'=>array(
			'table_name'=>'科目总账明细平衡表',
			'col'=>array('group_id'=>'站ID','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>109
		),
		'voucher_net_detail'=>array(
			'table_name'=>'明细净平衡表',
			'col'=>array('group_id'=>'站ID','deposit_money'=>'平台净存入','account_deposit'=>'账户净存入','pay_money'=>'平台净支出','account_pay'=>'账户净支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总平台净存入','field'=>'deposit_money'),
					array('name'=>'总平台净支出','field'=>'pay_money'),
					array('name'=>'总账户净存入','field'=>'account_deposit'),
					array('name'=>'总账户净支出','field'=>'account_pay')
				)
			),
			'child_id'=>111
		)
	),
	'kkyoo_voucher_plat'=>array(
		'voucher_user_ledger'=>array(
			'table_name'=>'用户总账平衡表',
			'col'=>array('deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>106
		),
		'voucher_parent_summary'=>array(
			'table_name'=>'科目汇总平衡表',
			'col'=>array('bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Core_three','Date_range'),
			'child_id'=>108
		),
		'voucher_parent_ledger_summary'=>array(
			'table_name'=>'科目总账汇总平衡表',
			'col'=>array('deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>110
		),
		'voucher_net_summary'=>array(
			'table_name'=>'汇总净平衡表',
			'col'=>array('deposit_money'=>'平台净存入','account_deposit'=>'账户净存入','pay_money'=>'平台净支出','account_pay'=>'账户净支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>112
		)
	),
	'kkyoo_tax'=>array(
		'tax_parent_balance'=>array(
			'table_name'=>'科目余额表',
			'col'=>array('group_id'=>'站ID','bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Core_three'),
			'statistics'=>array(
				'name'=>'科目总余额',
				'data'=>array(
					array('field'=>'last_balance')	
				)
			),
			'child_id'=>101
		),
		'tax_running'=>array(
			'table_name'=>'税收流水表',
			'col'=>array('group_id'=>'站ID','bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','child_name'=>'四级科目','uptime'=>'时间','trade_property'=>'交易属性','trade_type'=>'借贷','trade_money'=>'发生金额','parent_balance'=>'科目余额','trade_desc'=>'备注'),
			'searchField'=>array('Group_id','Core_four','Trade_info2','Date_range2'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'trade_money','other_where'=>'trade_type=1'),
					array('name'=>'总支出','field'=>'trade_money','other_where'=>'trade_type=2')
				)
			),
			'child_id'=>102
		),
		'tax_parent_detail'=>array(
			'table'=>'tax_parent_detail',
			'table_name'=>'科目明细平衡表',
			'col'=>array('group_id'=>'站ID','bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Core_three','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>103
		),
		'tax_ledger_detail'=>array(
			'table_name'=>'总账明细平衡表',
			'col'=>array('group_id'=>'站ID','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>105
		),
		'tax_net_detail'=>array(
			'table_name'=>'明细净平衡表',
			'col'=>array('group_id'=>'站ID','deposit_money'=>'平台净存入','account_deposit'=>'账户净存入','pay_money'=>'平台净支出','account_pay'=>'账户净支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Group_id','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总平台净存入','field'=>'deposit_money'),
					array('name'=>'总平台净支出','field'=>'pay_money'),
					array('name'=>'总账户净存入','field'=>'account_deposit'),
					array('name'=>'总账户净支出','field'=>'account_pay')
				)
			),
			'child_id'=>107
		)
	),
	'kkyoo_tax_plat'=>array(
		'tax_parent_summary'=>array(
			'table_name'=>'科目汇总平衡表',
			'col'=>array('bigcase_name'=>'一级科目','case_name'=>'二级科目','parent_name'=>'三级科目','deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','uptime'=>'时间'),
			'searchField'=>array('Core_three','Date_range'),
			'statistics'=>array(
				'name'=>'发生金额合计',
				'data'=>array(
					array('name'=>'总存入','field'=>'deposit_money'),
					array('name'=>'总支出','field'=>'pay_money')
				)
			),
			'child_id'=>104
		),
		'tax_ledger_summary'=>array(
			'table_name'=>'总账汇总平衡表',
			'col'=>array('deposit_money'=>'存入','pay_money'=>'支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>106
		),
		'tax_net_summary'=>array(
			'table_name'=>'汇总净平衡表',
			'col'=>array('deposit_money'=>'平台净存入','account_deposit'=>'账户净存入','pay_money'=>'平台净支出','account_pay'=>'账户净支出','last_balance'=>'余额','margin'=>'差额','uptime'=>'时间'),
			'searchField'=>array('Date_range'),
			'child_id'=>108
		)
	)
);
$link_array = array('kkyoo_kmoney'=>10334,'kkyoo_voucher'=>10335,'kkyoo_tax'=>10336,'kkyoo_voucher_plat'=>10731,'kkyoo_tax_plat'=>10732);